<?xml version="1.0" ?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="chassis_body" params="">

    <!-- Used for fixing robot to Gazebo 'chassis' -->
	<link name="base_footprint" />
	<link name="base_link" />

	<joint name="base_footprint_to_link" type="fixed">
		<parent link="base_footprint"/>
		<child link="base_link"/>
	</joint>

	<joint name="base_to_chassis" type="fixed">
		<parent link="base_link"/>
		<child link="chassis"/>
		<origin rpy="0 0 0" xyz="0 0 0"/>
	</joint>


	<link name='chassis'>
		<collision>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://simulation/models/lunar_pole_exploration_rover/meshes/chassis.dae" scale="${scale_XYZ} ${scale_XYZ} ${scale_XYZ}"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://simulation/models/lunar_pole_exploration_rover/meshes/chassis.dae" scale="${scale_XYZ} ${scale_XYZ} ${scale_XYZ}"/>
			</geometry>
		</visual>
		<inertial>
			<origin xyz="0 0 ${chassisHeight/2}"
					rpy="0 0 0"/>
			<mass value="${chassisMass}"/>
			<xacro:box_inertia
				m="${chassisMass}"
				x="${chassisWidth*scale_XYZ}"
				y="${chassisLength*scale_XYZ}"
				z="${chassisHeight*scale_XYZ}"/>
		</inertial>
	</link>

		<link name='body'>
		<collision>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://simulation/models/lunar_pole_exploration_rover/meshes/body.dae" scale="${scale_XYZ} ${scale_XYZ} ${scale_XYZ}"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://simulation/models/lunar_pole_exploration_rover/meshes/body.dae" scale="${scale_XYZ} ${scale_XYZ} ${scale_XYZ}"/>
			</geometry>
		</visual>
		<inertial>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<mass value="${bodyMass}"/>
			<xacro:box_inertia
				m="${bodyMass}"
				x="${bodyWidth*scale_XYZ}"
				y="${bodyLength*scale_XYZ}"
				z="${bodyHeight*scale_XYZ}"/>
		</inertial>
	</link>

	<joint name="chassis_body_joint" type="fixed">
    <parent link="chassis"/>
    <child link="body"/>
    <origin xyz="0.07 0.0 0.207" rpy="0 0 0"/>
  </joint>


	<link name='left_solar_panel'>
		<collision>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://simulation/models/lunar_pole_exploration_rover/meshes/solar_panel.dae" scale="${scale_XYZ} ${scale_XYZ} ${scale_XYZ}"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://simulation/models/lunar_pole_exploration_rover/meshes/solar_panel.dae" scale="${scale_XYZ} ${scale_XYZ} ${scale_XYZ}"/>
			</geometry>
		</visual>
		<inertial>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<mass value="${solarPanelMass}"/>
			<xacro:box_inertia
				m="${solarPanelMass}"
				x="${solarPanelWidth*scale_XYZ}"
				y="${solarPanelLength*scale_XYZ}"
				z="${solarPanelHeight*scale_XYZ}"/>
		</inertial>
	</link>

	<link name='right_solar_panel'>
		<collision>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://simulation/models/lunar_pole_exploration_rover/meshes/solar_panel.dae" scale="${scale_XYZ} ${scale_XYZ} ${scale_XYZ}"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://simulation/models/lunar_pole_exploration_rover/meshes/solar_panel.dae" scale="${scale_XYZ} ${scale_XYZ} ${scale_XYZ}"/>
			</geometry>
		</visual>
		<inertial>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<mass value="${solarPanelMass}"/>
			<xacro:box_inertia
				m="${solarPanelMass}"
				x="${solarPanelWidth*scale_XYZ}"
				y="${solarPanelLength*scale_XYZ}"
				z="${solarPanelHeight*scale_XYZ}"/>
		</inertial>
	</link>

	<link name='rear_solar_panel'>
		<collision>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://simulation/models/lunar_pole_exploration_rover/meshes/solar_panel.dae" scale="${scale_XYZ} ${scale_XYZ} ${scale_XYZ}"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://simulation/models/lunar_pole_exploration_rover/meshes/solar_panel.dae" scale="${scale_XYZ} ${scale_XYZ} ${scale_XYZ}"/>
			</geometry>
		</visual>
		<inertial>
			<origin xyz="0 0 0"
					rpy="0 0 0"/>
			<mass value="${solarPanelMass}"/>
			<xacro:box_inertia
				m="${solarPanelMass}"
				x="${solarPanelWidth*scale_XYZ}"
				y="${solarPanelLength*scale_XYZ}"
				z="${solarPanelHeight*scale_XYZ}"/>
		</inertial>
	</link>

	<joint name="left_solar_panel_joint" type="fixed">
    <parent link="body"/>
    <child link="left_solar_panel"/>
    <origin xyz="0.0252 0.7253 0.3829" rpy="-1.4673 0 ${PI}"/>
  </joint>

  <joint name="right_solar_panel_joint" type="fixed">
    <parent link="body"/>
    <child link="right_solar_panel"/>
    <origin xyz="0.0252 -0.7253 0.3829" rpy="1.4673 0 0"/>
  </joint>

  <joint name="rear_solar_panel_joint" type="fixed">
    <parent link="body"/>
    <child link="rear_solar_panel"/>
    <origin xyz="-0.7253 0.0 0.3829" rpy="1.4673 0 ${-PI/2}"/>
  </joint>

  </xacro:macro>
</robot>
